import { User } from '@altairgraphql/db';
import { PrismaService } from 'nestjs-prisma';
import { Prisma } from '@prisma/client';
import { StripeService } from 'src/stripe/stripe.service';
import { ProviderInfo } from '../models/provider-info.dto';
import { SignupInput } from '../models/signup.input';
import { UpdateUserInput } from '../models/update-user.input';
export declare class UserService {
    private readonly prisma;
    private readonly stripeService;
    private readonly logger;
    private readonly agent;
    constructor(prisma: PrismaService, stripeService: StripeService);
    createUser(payload: SignupInput, providerInfo?: ProviderInfo): Promise<User>;
    getUser(userId: string): Prisma.Prisma__UserClient<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    mustGetUser(userId: string): Promise<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getUserByStripeCustomerId(stripeCustomerId: string): Prisma.Prisma__UserClient<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    updateUser(userId: string, newUserData: UpdateUserInput): Prisma.Prisma__UserClient<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    updateUserResendContactId(userId: string, resendContactId: string): Prisma.Prisma__UserClient<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    getPlanConfig(userId: string): Promise<{
        id: string;
        stripeProductId: string | null;
        maxQueryCount: number;
        maxTeamCount: number;
        maxTeamMemberCount: number;
        queryRevisionLimit: number;
        allowMoreTeamMembers: boolean;
    } | null>;
    updateSubscriptionQuantity(userId: string, quantity: number): Promise<import("stripe").Stripe.Response<import("stripe").Stripe.SubscriptionItem> | undefined>;
    getStripeCustomerId(userId: string): Promise<string>;
    getBillingUrl(userId: string, returnUrl?: string): Promise<string>;
    getProPlanUrl(userId: string): Promise<string | null>;
    updateUserPlan(userId: string, planId: string, quantity: number): Promise<import("stripe").Stripe.Response<import("stripe").Stripe.SubscriptionItem> | undefined>;
    toBasicPlan(userId: string): Promise<void>;
    toProPlan(userId: string, quantity: number): Promise<void>;
    getProUsers(): Promise<{
        id: string;
        firstName: string | null;
        lastName: string | null;
        email: string;
        emailVerified: Date | null;
        password: string | null;
        picture: string | null;
        stripeCustomerId: string | null;
        resendContactId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
}
//# sourceMappingURL=user.service.d.ts.map